### ISSUE TITLE
Wildcard for allowed commands and flags

### ISSUE THREAD

**Issue by ichoosetoaccept** [MladenSU/cli-mcp-server#3]
I tried this
       "ALLOWED_COMMANDS": "",
        "ALLOWED_FLAGS": "",
but it does not seem to work. Is it possible to allow all? I understand the danger of this but I use ALLOWED_DIR for safety.

Thanks

**Comment by MladenSU** [comment]
Hello @ichoosetoaccept,

Thank you for your interest in the project and for bringing this to my attention.

I realize that the README was not updated with the latest information. You can indeed allow all commands and flags/parameters by using `"all"` in the configuration:

```json
  "mcpServers": {
    "cli-mcp-server": {
      "command": "uvx",
      "args": ["cli-mcp-server"],
      "env": {
        "ALLOWED_DIR": "<REDACTED>",
        "ALLOWED_COMMANDS": "all",
        "ALLOWED_FLAGS": "all",
      }
    }
 ```
 
 Then you can double-check if it worked by asking the client:
 
 ```
 🧑 User: Which commands are you allowed to execute in the CLI?
╰─❯ claude-3-5-sonnet-latest: 
I'll check the security rules to see what commands and operations are allowed in this environment.

▌ Triggered: show_security_rules.
Based on the security rules, I can execute:

 1 All commands
 2 All flags are allowed
 3 Commands must be:
    • Less than 1024 characters in length
    • Complete execution within 30 seconds
 ```
 
I will update the README shortly to reflect this information.

Please give it a try and let me know if you encounter any issues

Cheers

**Comment by ichoosetoaccept** [comment]
Hi @MladenSU 

Thanks for the swift response! After using the settings like you described and testing it with the same prompt as you, I can confirm that this does exactly what I wanted.

Thank you!

Cheers 😊

**Comment by MladenSU** [comment]
Glad to hear all is well. 

Have fun using it! 😊

Cheers!
